# Generated by Django 4.2.30 on 2026-06-22 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='exams.question'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionstopic',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', limit_choices_to={'level__in': [1, 2]}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.category'),
        ),
        migrations.AddField(
            model_name='notificationreceipt',
            name='notification',
            field=models.ForeignKey(db_column='notification_id', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='content.notification'),
        ),
        migrations.AddField(
            model_name='notificationreceipt',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notification_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_users',
            field=models.ManyToManyField(related_name='notifications', through='content.NotificationReceipt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examsection',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', limit_choices_to={'level__in': [1, 2]}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sections', to='content.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.category', verbose_name='Parent Category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(db_column='category_id', limit_choices_to={'level': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='content.category'),
        ),
        migrations.AddField(
            model_name='aiinstruction',
            name='question',
            field=models.ForeignKey(blank=True, db_column='question_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_instructions', to='exams.question'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['status'], name='testimonial_status_8d49e8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['user', 'status'], name='support_req_user_id_f15144_idx'),
        ),
        migrations.AddIndex(
            model_name='questionstopic',
            index=models.Index(fields=['category'], name='questions_t_categor_337b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationreceipt',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_132908_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationreceipt',
            unique_together={('notification', 'user')},
        ),
        migrations.AddIndex(
            model_name='examsection',
            index=models.Index(fields=['category'], name='exam_sectio_categor_60e4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status'], name='categories_status_dda6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'status'], name='categories_parent__6f950a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level', 'status'], name='categories_level_faba83_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_top', 'status'], name='categories_is_top_d18a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', '-created_at'], name='blogs_status_3796eb_idx'),
        ),
    ]
