# Generated by Django 4.2.30 on 2026-06-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_category_description_category_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
