# Generated by Django 4.2.30 on 2026-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_blog_author_image_blog_author_title_blog_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
