# Generated by Django 4.2.30 on 2026-06-28 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_blogcomment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['-is_featured', 'order', '-created_at']},
        ),
        migrations.AddField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='content.category'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='certificates_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructor',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AddField(
            model_name='instructor',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='twitter',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
