# Generated by Django 4.2.30 on 2026-06-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('marketer', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Percentage'), (2, 'Amount')])),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('quantity', models.IntegerField()),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'db_table': 'discounts_codes',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('icon', models.URLField(blank=True, max_length=500, null=True)),
                ('period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_questions', models.PositiveIntegerField(blank=True, null=True)),
                ('trial_count', models.PositiveIntegerField(default=0)),
                ('exam_count', models.PositiveIntegerField(default=0)),
                ('is_trial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 'packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package Exam',
                'verbose_name_plural': 'Package Exams',
                'db_table': 'package_exams',
            },
        ),
        migrations.CreateModel(
            name='PackageSubCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'packages_sub_categories',
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('price_before_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('pay_id', models.IntegerField(blank=True, null=True)),
                ('subscription_status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(db_column='package_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='packages.package')),
            ],
            options={
                'verbose_name': 'User Package',
                'verbose_name_plural': 'User Packages',
                'db_table': 'user_packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
