# Generated by Django 4.2.30 on 2026-06-22 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0003_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagesubcategorylink',
            name='package',
            field=models.ForeignKey(db_column='package_id', on_delete=django.db.models.deletion.CASCADE, related_name='package_sub_categories', to='packages.package'),
        ),
        migrations.AddField(
            model_name='packagesubcategorylink',
            name='sub_category',
            field=models.ForeignKey(db_column='sub_category_id', limit_choices_to={'level': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='package_sub_categories', to='content.category'),
        ),
        migrations.AddField(
            model_name='packageexam',
            name='exam',
            field=models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_exams', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='packageexam',
            name='package',
            field=models.ForeignKey(blank=True, db_column='package_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_exams', to='packages.package'),
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='content.category'),
        ),
        migrations.AddField(
            model_name='package',
            name='sub_categories',
            field=models.ManyToManyField(limit_choices_to={'level': 2}, related_name='packages_as_sub', through='packages.PackageSubCategoryLink', to='content.category'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['status', 'from_date', 'to_date'], name='discounts_c_status_2f008c_idx'),
        ),
        migrations.AddIndex(
            model_name='userpackage',
            index=models.Index(fields=['user', 'start_date', 'end_date'], name='user_packag_user_id_b8ee89_idx'),
        ),
        migrations.AddIndex(
            model_name='userpackage',
            index=models.Index(fields=['user', 'subscription_status'], name='user_packag_user_id_b6f359_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='packagesubcategorylink',
            unique_together={('sub_category', 'package')},
        ),
        migrations.AlterUniqueTogether(
            name='packageexam',
            unique_together={('package', 'exam')},
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['category', 'status'], name='packages_categor_6dfabc_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_trial', 'status'], name='packages_is_tria_03b917_idx'),
        ),
    ]
