# Generated by Django 4.2.30 on 2026-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
