# Generated by Django 4.2.30 on 2026-06-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_daily_rate_package_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
