# Generated by Django 4.2.30 on 2026-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_code_package_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
