# Generated by Django 4.2.30 on 2026-06-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_description_package_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='package',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
