# Generated by Django 4.2.30 on 2026-06-28 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_faq_alter_instructor_options_instructor_bio_and_more'),
        ('packages', '0006_package_difficulty_level_package_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='instructor',
            field=models.ForeignKey(blank=True, db_column='instructor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='content.instructor'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='lessons_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
