import type { LucideIcon } from 'lucide-react';
import {
  LayoutDashboard,
  Database,
  HelpCircle,
  Stethoscope,
  Layers,
  GitBranch,
  Tag,
  BookOpen,
  ClipboardList,
  FileText,
  Users,
  GraduationCap,
  CreditCard,
  ShoppingCart,
  Wallet,
  Award,
  Percent,
  Newspaper,
  MessageSquare,
  Bell,
  Ticket,
  BarChart3,
  LineChart,
  Shield,
  UserCog,
  Settings,
} from 'lucide-react';

export interface AdminMenuItem {
  id: string;
  labelKey: string;
  icon: LucideIcon;
  to: string;
}

export const adminMenu: AdminMenuItem[] = [
  { id: 'dashboard', labelKey: 'admin.modules.dashboard', icon: LayoutDashboard, to: '/admin' },
  { id: 'questionBanks', labelKey: 'admin.modules.questionBanks', icon: Database, to: '/admin/question-banks' },
  { id: 'questions', labelKey: 'admin.modules.questions', icon: HelpCircle, to: '/admin/questions' },
  { id: 'specialties', labelKey: 'admin.modules.specialties', icon: Stethoscope, to: '/admin/specialties' },
  { id: 'categories', labelKey: 'admin.modules.categories', icon: Layers, to: '/admin/categories' },
  { id: 'subCategories', labelKey: 'admin.modules.subCategories', icon: GitBranch, to: '/admin/sub-categories' },
  { id: 'topics', labelKey: 'admin.modules.topics', icon: Tag, to: '/admin/topics' },
  { id: 'courses', labelKey: 'admin.modules.courses', icon: BookOpen, to: '/admin/courses' },
  { id: 'exams', labelKey: 'admin.modules.exams', icon: ClipboardList, to: '/admin/exams' },
  { id: 'examTemplates', labelKey: 'admin.modules.examTemplates', icon: FileText, to: '/admin/exam-templates' },
  { id: 'students', labelKey: 'admin.modules.students', icon: Users, to: '/admin/students' },
  { id: 'instructors', labelKey: 'admin.modules.instructors', icon: GraduationCap, to: '/admin/instructors' },
  { id: 'subscriptions', labelKey: 'admin.modules.subscriptions', icon: CreditCard, to: '/admin/subscriptions' },
  { id: 'orders', labelKey: 'admin.modules.orders', icon: ShoppingCart, to: '/admin/orders' },
  { id: 'payments', labelKey: 'admin.modules.payments', icon: Wallet, to: '/admin/payments' },
  { id: 'certificates', labelKey: 'admin.modules.certificates', icon: Award, to: '/admin/certificates' },
  { id: 'offers', labelKey: 'admin.modules.offers', icon: Percent, to: '/admin/offers' },
  { id: 'blog', labelKey: 'admin.modules.blog', icon: Newspaper, to: '/admin/blog' },
  { id: 'pages', labelKey: 'admin.modules.pages', icon: FileText, to: '/admin/pages' },
  { id: 'testimonials', labelKey: 'admin.modules.testimonials', icon: MessageSquare, to: '/admin/testimonials' },
  { id: 'notifications', labelKey: 'admin.modules.notifications', icon: Bell, to: '/admin/notifications' },
  { id: 'supportTickets', labelKey: 'admin.modules.supportTickets', icon: Ticket, to: '/admin/support-tickets' },
  { id: 'reports', labelKey: 'admin.modules.reports', icon: BarChart3, to: '/admin/reports' },
  { id: 'analytics', labelKey: 'admin.modules.analytics', icon: LineChart, to: '/admin/analytics' },
  { id: 'roles', labelKey: 'admin.modules.roles', icon: Shield, to: '/admin/roles' },
  { id: 'users', labelKey: 'admin.modules.users', icon: UserCog, to: '/admin/users' },
  { id: 'settings', labelKey: 'admin.modules.settings', icon: Settings, to: '/admin/settings' },
];

export interface ColumnDef {
  key: string;
  labelKey: string;
  type?: 'text' | 'status' | 'date' | 'number';
}

export interface AdminEntityConfig {
  id: string;
  labelKey: string;
  pluralKey: string;
  parent?: string;
  columns: ColumnDef[];
  stats: { key: string; labelKey: string; icon: LucideIcon; color: string }[];
}

export const entityConfig: Record<string, AdminEntityConfig> = {
  'question-banks': {
    id: 'question-banks',
    labelKey: 'admin.modules.questionBanks',
    pluralKey: 'admin.modules.questionBanks',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'topic', labelKey: 'admin.modules.topics', type: 'text' },
      { key: 'questions', labelKey: 'admin.modules.questions', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.questionBanks', icon: Database, color: 'bg-blue-100 text-blue-600' },
      { key: 'questions', labelKey: 'admin.dashboardHome.totalQuestions', icon: HelpCircle, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'active', labelKey: 'admin.filters.active', icon: Layers, color: 'bg-primary/10 text-primary' },
      { key: 'archived', labelKey: 'admin.filters.archived', icon: Database, color: 'bg-slate-100 text-slate-600' },
    ],
  },
  questions: {
    id: 'questions',
    labelKey: 'admin.modules.questions',
    pluralKey: 'admin.modules.questions',
    parent: 'question-banks',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'title', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'type', labelKey: 'admin.entity.type', type: 'text' },
      { key: 'difficulty', labelKey: 'admin.entity.difficulty', type: 'text' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.dashboardHome.totalQuestions', icon: HelpCircle, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'single', labelKey: 'admin.entity.singleChoice', icon: HelpCircle, color: 'bg-blue-100 text-blue-600' },
      { key: 'multiple', labelKey: 'admin.entity.multipleChoice', icon: HelpCircle, color: 'bg-purple-100 text-purple-600' },
      { key: 'image', labelKey: 'admin.entity.imageBased', icon: HelpCircle, color: 'bg-amber-100 text-amber-600' },
    ],
  },
  specialties: {
    id: 'specialties',
    labelKey: 'admin.modules.specialties',
    pluralKey: 'admin.modules.specialties',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'categories', labelKey: 'admin.modules.categories', type: 'number' },
      { key: 'questions', labelKey: 'admin.modules.questions', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.specialties', icon: Stethoscope, color: 'bg-primary/10 text-primary' },
      { key: 'categories', labelKey: 'admin.modules.categories', icon: Layers, color: 'bg-blue-100 text-blue-600' },
      { key: 'questions', labelKey: 'admin.dashboardHome.totalQuestions', icon: HelpCircle, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'active', labelKey: 'admin.filters.active', icon: Stethoscope, color: 'bg-amber-100 text-amber-600' },
    ],
  },
  categories: {
    id: 'categories',
    labelKey: 'admin.modules.categories',
    pluralKey: 'admin.modules.categories',
    parent: 'specialties',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'specialty', labelKey: 'admin.modules.specialties', type: 'text' },
      { key: 'subCategories', labelKey: 'admin.modules.subCategories', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.categories', icon: Layers, color: 'bg-blue-100 text-blue-600' },
      { key: 'specialties', labelKey: 'admin.modules.specialties', icon: Stethoscope, color: 'bg-primary/10 text-primary' },
      { key: 'subCategories', labelKey: 'admin.modules.subCategories', icon: GitBranch, color: 'bg-purple-100 text-purple-600' },
      { key: 'active', labelKey: 'admin.filters.active', icon: Layers, color: 'bg-emerald-100 text-emerald-600' },
    ],
  },
  'sub-categories': {
    id: 'sub-categories',
    labelKey: 'admin.modules.subCategories',
    pluralKey: 'admin.modules.subCategories',
    parent: 'categories',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'category', labelKey: 'admin.modules.categories', type: 'text' },
      { key: 'topics', labelKey: 'admin.modules.topics', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.subCategories', icon: GitBranch, color: 'bg-purple-100 text-purple-600' },
      { key: 'categories', labelKey: 'admin.modules.categories', icon: Layers, color: 'bg-blue-100 text-blue-600' },
      { key: 'topics', labelKey: 'admin.modules.topics', icon: Tag, color: 'bg-amber-100 text-amber-600' },
      { key: 'active', labelKey: 'admin.filters.active', icon: GitBranch, color: 'bg-emerald-100 text-emerald-600' },
    ],
  },
  topics: {
    id: 'topics',
    labelKey: 'admin.modules.topics',
    pluralKey: 'admin.modules.topics',
    parent: 'sub-categories',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'subCategory', labelKey: 'admin.modules.subCategories', type: 'text' },
      { key: 'questions', labelKey: 'admin.modules.questions', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.topics', icon: Tag, color: 'bg-amber-100 text-amber-600' },
      { key: 'questions', labelKey: 'admin.dashboardHome.totalQuestions', icon: HelpCircle, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'subCategories', labelKey: 'admin.modules.subCategories', icon: GitBranch, color: 'bg-purple-100 text-purple-600' },
      { key: 'active', labelKey: 'admin.filters.active', icon: Tag, color: 'bg-primary/10 text-primary' },
    ],
  },
  courses: {
    id: 'courses',
    labelKey: 'admin.modules.courses',
    pluralKey: 'admin.modules.courses',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'instructor', labelKey: 'admin.modules.instructors', type: 'text' },
      { key: 'students', labelKey: 'admin.modules.students', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.dashboardHome.totalCourses', icon: BookOpen, color: 'bg-blue-100 text-blue-600' },
      { key: 'students', labelKey: 'admin.modules.students', icon: Users, color: 'bg-primary/10 text-primary' },
      { key: 'active', labelKey: 'admin.filters.active', icon: BookOpen, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'revenue', labelKey: 'admin.dashboardHome.revenue', icon: Wallet, color: 'bg-amber-100 text-amber-600' },
    ],
  },
  exams: {
    id: 'exams',
    labelKey: 'admin.modules.exams',
    pluralKey: 'admin.modules.exams',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'students', labelKey: 'admin.modules.students', type: 'number' },
      { key: 'questions', labelKey: 'admin.modules.questions', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.dashboardHome.totalExams', icon: ClipboardList, color: 'bg-purple-100 text-purple-600' },
      { key: 'students', labelKey: 'admin.modules.students', icon: Users, color: 'bg-primary/10 text-primary' },
      { key: 'active', labelKey: 'admin.filters.active', icon: ClipboardList, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'avgScore', labelKey: 'admin.dashboardHome.passRate', icon: BarChart3, color: 'bg-blue-100 text-blue-600' },
    ],
  },
  'exam-templates': {
    id: 'exam-templates',
    labelKey: 'admin.modules.examTemplates',
    pluralKey: 'admin.modules.examTemplates',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'mode', labelKey: 'admin.entity.mode', type: 'text' },
      { key: 'questions', labelKey: 'admin.modules.questions', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.examTemplates', icon: FileText, color: 'bg-slate-100 text-slate-600' },
      { key: 'active', labelKey: 'admin.filters.active', icon: FileText, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'mock', labelKey: 'admin.entity.mock', icon: FileText, color: 'bg-blue-100 text-blue-600' },
      { key: 'final', labelKey: 'admin.entity.final', icon: FileText, color: 'bg-amber-100 text-amber-600' },
    ],
  },
  students: {
    id: 'students',
    labelKey: 'admin.modules.students',
    pluralKey: 'admin.modules.students',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'email', labelKey: 'admin.entity.email', type: 'text' },
      { key: 'exams', labelKey: 'admin.modules.exams', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.dashboardHome.totalStudents', icon: Users, color: 'bg-primary/10 text-primary' },
      { key: 'active', labelKey: 'admin.dashboardHome.activeStudents', icon: Users, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'exams', labelKey: 'admin.dashboardHome.totalExams', icon: ClipboardList, color: 'bg-purple-100 text-purple-600' },
      { key: 'certificates', labelKey: 'admin.dashboardHome.certificates', icon: Award, color: 'bg-amber-100 text-amber-600' },
    ],
  },
  instructors: {
    id: 'instructors',
    labelKey: 'admin.modules.instructors',
    pluralKey: 'admin.modules.instructors',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'specialty', labelKey: 'admin.modules.specialties', type: 'text' },
      { key: 'courses', labelKey: 'admin.modules.courses', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.instructors', icon: GraduationCap, color: 'bg-blue-100 text-blue-600' },
      { key: 'courses', labelKey: 'admin.dashboardHome.totalCourses', icon: BookOpen, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'active', labelKey: 'admin.filters.active', icon: GraduationCap, color: 'bg-primary/10 text-primary' },
      { key: 'students', labelKey: 'admin.modules.students', icon: Users, color: 'bg-amber-100 text-amber-600' },
    ],
  },
  subscriptions: {
    id: 'subscriptions',
    labelKey: 'admin.modules.subscriptions',
    pluralKey: 'admin.modules.subscriptions',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'student', labelKey: 'admin.modules.students', type: 'text' },
      { key: 'package', labelKey: 'admin.entity.package', type: 'text' },
      { key: 'endDate', labelKey: 'admin.entity.endDate', type: 'date' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.dashboardHome.activeSubscriptions', icon: CreditCard, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'monthly', labelKey: 'admin.entity.monthly', icon: CreditCard, color: 'bg-primary/10 text-primary' },
      { key: 'revenue', labelKey: 'admin.dashboardHome.revenue', icon: Wallet, color: 'bg-amber-100 text-amber-600' },
      { key: 'expiring', labelKey: 'admin.entity.expiring', icon: CreditCard, color: 'bg-rose-100 text-rose-600' },
    ],
  },
  orders: {
    id: 'orders',
    labelKey: 'admin.modules.orders',
    pluralKey: 'admin.modules.orders',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'student', labelKey: 'admin.modules.students', type: 'text' },
      { key: 'amount', labelKey: 'admin.entity.amount', type: 'text' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'date', labelKey: 'admin.entity.date', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.orders', icon: ShoppingCart, color: 'bg-blue-100 text-blue-600' },
      { key: 'revenue', labelKey: 'admin.dashboardHome.revenue', icon: Wallet, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'pending', labelKey: 'admin.entity.pending', icon: ShoppingCart, color: 'bg-amber-100 text-amber-600' },
      { key: 'completed', labelKey: 'admin.entity.completed', icon: ShoppingCart, color: 'bg-primary/10 text-primary' },
    ],
  },
  payments: {
    id: 'payments',
    labelKey: 'admin.modules.payments',
    pluralKey: 'admin.modules.payments',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'student', labelKey: 'admin.modules.students', type: 'text' },
      { key: 'method', labelKey: 'admin.entity.method', type: 'text' },
      { key: 'amount', labelKey: 'admin.entity.amount', type: 'text' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'date', labelKey: 'admin.entity.date', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.payments', icon: Wallet, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'revenue', labelKey: 'admin.dashboardHome.revenue', icon: Wallet, color: 'bg-amber-100 text-amber-600' },
      { key: 'successful', labelKey: 'admin.entity.successful', icon: Wallet, color: 'bg-primary/10 text-primary' },
      { key: 'failed', labelKey: 'admin.entity.failed', icon: Wallet, color: 'bg-rose-100 text-rose-600' },
    ],
  },
  certificates: {
    id: 'certificates',
    labelKey: 'admin.modules.certificates',
    pluralKey: 'admin.modules.certificates',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'student', labelKey: 'admin.modules.students', type: 'text' },
      { key: 'course', labelKey: 'admin.modules.courses', type: 'text' },
      { key: 'issueDate', labelKey: 'admin.entity.issueDate', type: 'date' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.dashboardHome.certificates', icon: Award, color: 'bg-amber-100 text-amber-600' },
      { key: 'thisMonth', labelKey: 'admin.entity.thisMonth', icon: Award, color: 'bg-primary/10 text-primary' },
      { key: 'students', labelKey: 'admin.modules.students', icon: Users, color: 'bg-blue-100 text-blue-600' },
      { key: 'verified', labelKey: 'admin.entity.verified', icon: Award, color: 'bg-emerald-100 text-emerald-600' },
    ],
  },
  offers: {
    id: 'offers',
    labelKey: 'admin.modules.offers',
    pluralKey: 'admin.modules.offers',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'code', labelKey: 'admin.entity.code', type: 'text' },
      { key: 'discount', labelKey: 'admin.entity.discount', type: 'text' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.offers', icon: Percent, color: 'bg-purple-100 text-purple-600' },
      { key: 'active', labelKey: 'admin.filters.active', icon: Percent, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'used', labelKey: 'admin.entity.used', icon: Percent, color: 'bg-amber-100 text-amber-600' },
      { key: 'revenue', labelKey: 'admin.dashboardHome.revenue', icon: Wallet, color: 'bg-primary/10 text-primary' },
    ],
  },
  blog: {
    id: 'blog',
    labelKey: 'admin.modules.blog',
    pluralKey: 'admin.modules.blog',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'title', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'author', labelKey: 'admin.entity.author', type: 'text' },
      { key: 'views', labelKey: 'admin.entity.views', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.blog', icon: Newspaper, color: 'bg-blue-100 text-blue-600' },
      { key: 'views', labelKey: 'admin.entity.views', icon: BarChart3, color: 'bg-primary/10 text-primary' },
      { key: 'published', labelKey: 'admin.entity.published', icon: Newspaper, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'draft', labelKey: 'admin.entity.draft', icon: Newspaper, color: 'bg-amber-100 text-amber-600' },
    ],
  },
  pages: {
    id: 'pages',
    labelKey: 'admin.modules.pages',
    pluralKey: 'admin.modules.pages',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'title', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'slug', labelKey: 'admin.entity.slug', type: 'text' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.pages', icon: FileText, color: 'bg-slate-100 text-slate-600' },
      { key: 'published', labelKey: 'admin.entity.published', icon: FileText, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'draft', labelKey: 'admin.entity.draft', icon: FileText, color: 'bg-amber-100 text-amber-600' },
      { key: 'archived', labelKey: 'admin.filters.archived', icon: FileText, color: 'bg-rose-100 text-rose-600' },
    ],
  },
  testimonials: {
    id: 'testimonials',
    labelKey: 'admin.modules.testimonials',
    pluralKey: 'admin.modules.testimonials',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'role', labelKey: 'admin.entity.role', type: 'text' },
      { key: 'rating', labelKey: 'admin.entity.rating', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.testimonials', icon: MessageSquare, color: 'bg-primary/10 text-primary' },
      { key: 'published', labelKey: 'admin.entity.published', icon: MessageSquare, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'avgRating', labelKey: 'admin.entity.avgRating', icon: BarChart3, color: 'bg-amber-100 text-amber-600' },
      { key: 'pending', labelKey: 'admin.entity.pending', icon: MessageSquare, color: 'bg-rose-100 text-rose-600' },
    ],
  },
  notifications: {
    id: 'notifications',
    labelKey: 'admin.modules.notifications',
    pluralKey: 'admin.modules.notifications',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'title', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'audience', labelKey: 'admin.entity.audience', type: 'text' },
      { key: 'sent', labelKey: 'admin.entity.sent', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.notifications', icon: Bell, color: 'bg-blue-100 text-blue-600' },
      { key: 'sent', labelKey: 'admin.entity.sent', icon: Bell, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'scheduled', labelKey: 'admin.entity.scheduled', icon: Bell, color: 'bg-amber-100 text-amber-600' },
      { key: 'failed', labelKey: 'admin.entity.failed', icon: Bell, color: 'bg-rose-100 text-rose-600' },
    ],
  },
  'support-tickets': {
    id: 'support-tickets',
    labelKey: 'admin.modules.supportTickets',
    pluralKey: 'admin.modules.supportTickets',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'subject', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'student', labelKey: 'admin.modules.students', type: 'text' },
      { key: 'priority', labelKey: 'admin.entity.priority', type: 'text' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.supportTickets', icon: Ticket, color: 'bg-slate-100 text-slate-600' },
      { key: 'open', labelKey: 'admin.entity.open', icon: Ticket, color: 'bg-rose-100 text-rose-600' },
      { key: 'resolved', labelKey: 'admin.entity.resolved', icon: Ticket, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'avgResponse', labelKey: 'admin.entity.avgResponse', icon: Ticket, color: 'bg-primary/10 text-primary' },
    ],
  },
  reports: {
    id: 'reports',
    labelKey: 'admin.modules.reports',
    pluralKey: 'admin.modules.reports',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'type', labelKey: 'admin.entity.type', type: 'text' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.reports', icon: BarChart3, color: 'bg-blue-100 text-blue-600' },
      { key: 'generated', labelKey: 'admin.entity.generated', icon: BarChart3, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'scheduled', labelKey: 'admin.entity.scheduled', icon: BarChart3, color: 'bg-amber-100 text-amber-600' },
      { key: 'downloads', labelKey: 'admin.entity.downloads', icon: BarChart3, color: 'bg-primary/10 text-primary' },
    ],
  },
  analytics: {
    id: 'analytics',
    labelKey: 'admin.modules.analytics',
    pluralKey: 'admin.modules.analytics',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'metric', labelKey: 'admin.entity.metric', type: 'text' },
      { key: 'value', labelKey: 'admin.entity.value', type: 'text' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.analytics', icon: LineChart, color: 'bg-purple-100 text-purple-600' },
      { key: 'students', labelKey: 'admin.modules.students', icon: Users, color: 'bg-primary/10 text-primary' },
      { key: 'exams', labelKey: 'admin.modules.exams', icon: ClipboardList, color: 'bg-blue-100 text-blue-600' },
      { key: 'passRate', labelKey: 'admin.dashboardHome.passRate', icon: LineChart, color: 'bg-emerald-100 text-emerald-600' },
    ],
  },
  roles: {
    id: 'roles',
    labelKey: 'admin.modules.roles',
    pluralKey: 'admin.modules.roles',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'users', labelKey: 'admin.modules.users', type: 'number' },
      { key: 'permissions', labelKey: 'admin.entity.permissions', type: 'number' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.roles', icon: Shield, color: 'bg-slate-100 text-slate-600' },
      { key: 'users', labelKey: 'admin.modules.users', icon: UserCog, color: 'bg-primary/10 text-primary' },
      { key: 'active', labelKey: 'admin.filters.active', icon: Shield, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'permissions', labelKey: 'admin.entity.permissions', icon: Shield, color: 'bg-blue-100 text-blue-600' },
    ],
  },
  users: {
    id: 'users',
    labelKey: 'admin.modules.users',
    pluralKey: 'admin.modules.users',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
      { key: 'email', labelKey: 'admin.entity.email', type: 'text' },
      { key: 'role', labelKey: 'admin.modules.roles', type: 'text' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
      { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.users', icon: UserCog, color: 'bg-blue-100 text-blue-600' },
      { key: 'active', labelKey: 'admin.filters.active', icon: UserCog, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'admins', labelKey: 'admin.entity.admins', icon: Shield, color: 'bg-amber-100 text-amber-600' },
      { key: 'newThisMonth', labelKey: 'admin.entity.newThisMonth', icon: UserCog, color: 'bg-primary/10 text-primary' },
    ],
  },
  settings: {
    id: 'settings',
    labelKey: 'admin.modules.settings',
    pluralKey: 'admin.modules.settings',
    columns: [
      { key: 'id', labelKey: 'admin.table.id', type: 'number' },
      { key: 'key', labelKey: 'admin.entity.key', type: 'text' },
      { key: 'value', labelKey: 'admin.entity.value', type: 'text' },
      { key: 'group', labelKey: 'admin.entity.group', type: 'text' },
      { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
    ],
    stats: [
      { key: 'total', labelKey: 'admin.modules.settings', icon: Settings, color: 'bg-slate-100 text-slate-600' },
      { key: 'general', labelKey: 'admin.entity.general', icon: Settings, color: 'bg-primary/10 text-primary' },
      { key: 'payment', labelKey: 'admin.entity.payment', icon: Wallet, color: 'bg-emerald-100 text-emerald-600' },
      { key: 'notifications', labelKey: 'admin.modules.notifications', icon: Bell, color: 'bg-amber-100 text-amber-600' },
    ],
  },
};

export const defaultColumns: ColumnDef[] = [
  { key: 'id', labelKey: 'admin.table.id', type: 'number' },
  { key: 'name', labelKey: 'admin.entity.name', type: 'text' },
  { key: 'status', labelKey: 'admin.filters.status', type: 'status' },
  { key: 'created_at', labelKey: 'admin.entity.createdAt', type: 'date' },
];
