# Generated by Django 4.2.30 on 2026-06-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'questions_answers',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.URLField(blank=True, max_length=500, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('show_hint', models.BooleanField(default=False)),
                ('show_answer', models.BooleanField(default=False)),
                ('video_link', models.URLField(blank=True, max_length=500, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
                'db_table': 'exam_questions',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSectionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Section Link',
                'verbose_name_plural': 'Exam Section Links',
                'db_table': 'exam_sections',
            },
        ),
        migrations.CreateModel(
            name='ExamTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(choices=[('tatur', 'Tutor Mode'), ('exam', 'Exam Mode')], default='tatur', max_length=10)),
                ('is_timed_mode', models.BooleanField(default=False)),
                ('question_mode', models.CharField(choices=[('all', 'All'), ('unused', 'Unused'), ('used', 'Used'), ('correct', 'Correct'), ('incorrect', 'Incorrect'), ('omitted', 'Omitted'), ('marked', 'Marked')], default='all', max_length=10)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('stages', models.JSONField(blank=True, null=True)),
                ('current_stage', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exam Trail',
                'verbose_name_plural': 'Exam Trails',
                'db_table': 'exam_trails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamTrailCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'categories_exam_trails',
            },
        ),
        migrations.CreateModel(
            name='ExamTrailSectionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'exam_trails_sections',
            },
        ),
        migrations.CreateModel(
            name='ExamTrailSubCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sub_categories_exam_trails',
            },
        ),
        migrations.CreateModel(
            name='ExamTrailSubSubCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sub_sub_categories_exam_trails',
            },
        ),
        migrations.CreateModel(
            name='ExamTrailTopicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'exam_trails_topics',
            },
        ),
        migrations.CreateModel(
            name='ExamTrialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('is_marked', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Trial Detail',
                'verbose_name_plural': 'Exam Trial Details',
                'db_table': 'exam_trial_details',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('question_type', models.IntegerField(blank=True, choices=[(0, 'Empty'), (1, 'Question'), (2, 'Text')], null=True)),
                ('answer_type', models.IntegerField(blank=True, choices=[(1, 'Radio'), (2, 'Multiple Choice')], null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('show_answer_explanation', models.BooleanField(default=False)),
                ('show_hint', models.BooleanField(default=False)),
                ('show_answer', models.BooleanField(default=False)),
                ('show_video', models.BooleanField(default=False)),
                ('video_link', models.URLField(blank=True, max_length=500, null=True)),
                ('time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('question_has_image', models.BooleanField(default=False)),
                ('question_image', models.URLField(blank=True, max_length=500, null=True)),
                ('answer_has_image', models.BooleanField(default=False)),
                ('answer_image', models.URLField(blank=True, max_length=500, null=True)),
                ('sort_order', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Topic',
                'verbose_name_plural': 'Question Topics',
                'db_table': 'question_topics',
            },
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Submitted')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Exam',
                'verbose_name_plural': 'User Exams',
                'db_table': 'user_exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Exam Answer',
                'verbose_name_plural': 'User Exam Answers',
                'db_table': 'user_exam_questions_answers',
            },
        ),
        migrations.CreateModel(
            name='UserExamTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_trials', to='exams.exam')),
            ],
            options={
                'verbose_name': 'User Exam Trial',
                'verbose_name_plural': 'User Exam Trials',
                'db_table': 'user_exam_trials',
            },
        ),
    ]
