# Generated by Django 4.2.30 on 2026-06-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamtrial',
            name='subscription',
            field=models.ForeignKey(blank=True, db_column='subscription_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_trials', to='packages.userpackage'),
        ),
    ]
