# Generated by Django 4.2.30 on 2026-06-22 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamtrial',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_trials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='exam',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_answers', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_answers', to='exams.question'),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='user_exam',
            field=models.ForeignKey(blank=True, db_column='user_exam_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.userexam'),
        ),
        migrations.AddField(
            model_name='userexam',
            name='exam',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='userexam',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='question_topics', to='exams.question'),
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='topic',
            field=models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, related_name='question_topics', to='content.questionstopic'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(blank=True, db_column='correct_answer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_correct_for', to='exams.answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_category',
            field=models.ForeignKey(blank=True, db_column='sub_category_id', limit_choices_to={'level': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_as_sub', to='content.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_subcategory',
            field=models.ForeignKey(blank=True, db_column='sub_subcategory_id', limit_choices_to={'level': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_as_sub_sub', to='content.category'),
        ),
        migrations.AddField(
            model_name='examtrialdetail',
            name='answer',
            field=models.ForeignKey(blank=True, db_column='answer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_details', to='exams.answer'),
        ),
        migrations.AddField(
            model_name='examtrialdetail',
            name='exam_trail',
            field=models.ForeignKey(db_column='exam_trial_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='exams.examtrail'),
        ),
        migrations.AddField(
            model_name='examtrialdetail',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='trial_details', to='exams.question'),
        ),
        migrations.AddField(
            model_name='examtrailtopiclink',
            name='exam_trail',
            field=models.ForeignKey(db_column='exam_trail_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_trail_topics', to='exams.examtrail'),
        ),
        migrations.AddField(
            model_name='examtrailtopiclink',
            name='topic',
            field=models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_trail_topics', to='content.questionstopic'),
        ),
        migrations.AddField(
            model_name='examtrailsubsubcategorylink',
            name='exam_trail',
            field=models.ForeignKey(db_column='exam_trail_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_trail_sub_sub_categories', to='exams.examtrail'),
        ),
        migrations.AddField(
            model_name='examtrailsubsubcategorylink',
            name='sub_sub_category',
            field=models.ForeignKey(db_column='sub_sub_category_id', limit_choices_to={'level': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_trail_sub_sub_categories', to='content.category'),
        ),
        migrations.AddField(
            model_name='examtrailsubcategorylink',
            name='exam_trail',
            field=models.ForeignKey(db_column='exam_trail_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_trail_sub_categories', to='exams.examtrail'),
        ),
        migrations.AddField(
            model_name='examtrailsubcategorylink',
            name='sub_category',
            field=models.ForeignKey(db_column='sub_category_id', limit_choices_to={'level': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_trail_sub_categories', to='content.category'),
        ),
        migrations.AddField(
            model_name='examtrailsectionlink',
            name='exam_trail',
            field=models.ForeignKey(db_column='exam_trail_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_trail_sections', to='exams.examtrail'),
        ),
        migrations.AddField(
            model_name='examtrailsectionlink',
            name='section',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_trail_sections', to='content.examsection'),
        ),
        migrations.AddField(
            model_name='examtrailcategorylink',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_trail_categories', to='content.category'),
        ),
        migrations.AddField(
            model_name='examtrailcategorylink',
            name='exam_trail',
            field=models.ForeignKey(db_column='exam_trail_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_trail_categories', to='exams.examtrail'),
        ),
        migrations.AddField(
            model_name='examtrail',
            name='categories',
            field=models.ManyToManyField(related_name='exam_trails', through='exams.ExamTrailCategoryLink', to='content.category'),
        ),
        migrations.AddField(
            model_name='examtrail',
            name='questions',
            field=models.ManyToManyField(related_name='exam_trails', through='exams.ExamTrialDetail', to='exams.question'),
        ),
        migrations.AddField(
            model_name='examtrail',
            name='sections',
            field=models.ManyToManyField(related_name='exam_trails', through='exams.ExamTrailSectionLink', to='content.examsection'),
        ),
        migrations.AddField(
            model_name='examtrail',
            name='sub_categories',
            field=models.ManyToManyField(related_name='exam_trails_as_sub', through='exams.ExamTrailSubCategoryLink', to='content.category'),
        ),
        migrations.AddField(
            model_name='examtrail',
            name='sub_sub_categories',
            field=models.ManyToManyField(related_name='exam_trails_as_sub_sub', through='exams.ExamTrailSubSubCategoryLink', to='content.category'),
        ),
        migrations.AddField(
            model_name='examtrail',
            name='topics',
            field=models.ManyToManyField(related_name='exam_trails', through='exams.ExamTrailTopicLink', to='content.questionstopic'),
        ),
        migrations.AddField(
            model_name='examtrail',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_trails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examsectionlink',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_section_links', to='exams.question'),
        ),
        migrations.AddField(
            model_name='examsectionlink',
            name='section',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_section_links', to='content.examsection'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.question'),
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(blank=True, db_column='cat_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='content.category'),
        ),
        migrations.AddField(
            model_name='exam',
            name='sub_category',
            field=models.ForeignKey(blank=True, db_column='sub_cat_id', limit_choices_to={'level': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams_as_sub', to='content.category'),
        ),
        migrations.AddField(
            model_name='exam',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, db_column='sub_sub_cat_id', limit_choices_to={'level': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams_as_sub_sub', to='content.category'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question'),
        ),
        migrations.AddIndex(
            model_name='userexamtrial',
            index=models.Index(fields=['user', 'exam'], name='user_exam_t_user_id_8162f1_idx'),
        ),
        migrations.AddIndex(
            model_name='userexamanswer',
            index=models.Index(fields=['user_exam'], name='user_exam_q_user_ex_6a7c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='userexamanswer',
            index=models.Index(fields=['user', 'exam'], name='user_exam_q_user_id_4e1999_idx'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['user', 'status'], name='user_exams_user_id_5c35d5_idx'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['user', 'exam'], name='user_exams_user_id_768b25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questiontopic',
            unique_together={('question', 'topic')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status'], name='questions_status_7bb3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'sub_category', 'sub_subcategory'], name='questions_categor_4a367c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='questions_categor_88b3fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examtrialdetail',
            unique_together={('exam_trail', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='examtrailtopiclink',
            unique_together={('exam_trail', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='examtrailsubsubcategorylink',
            unique_together={('exam_trail', 'sub_sub_category')},
        ),
        migrations.AlterUniqueTogether(
            name='examtrailsubcategorylink',
            unique_together={('exam_trail', 'sub_category')},
        ),
        migrations.AlterUniqueTogether(
            name='examtrailsectionlink',
            unique_together={('exam_trail', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='examtrailcategorylink',
            unique_together={('exam_trail', 'category')},
        ),
        migrations.AddIndex(
            model_name='examtrail',
            index=models.Index(fields=['user', '-created_at'], name='exam_trails_user_id_295c44_idx'),
        ),
        migrations.AddIndex(
            model_name='examtrail',
            index=models.Index(fields=['status'], name='exam_trails_status_20eae3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsectionlink',
            unique_together={('question', 'section')},
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'order'], name='exam_questi_exam_id_a0918d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('exam', 'question')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status'], name='exams_status_863d01_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['category', 'sub_category', 'sub_sub_category'], name='exams_cat_id_9b0edd_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='questions_a_questio_63d113_idx'),
        ),
    ]
