# Generated by Django 4.2.30 on 2026-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='attempts_allowed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='certificate_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
