# Generated by Django 4.2.30 on 2026-06-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_faq_alter_instructor_options_instructor_bio_and_more'),
        ('exams', '0004_exam_attempts_allowed_exam_certificate_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('mock', 'Mock Exam'), ('practice', 'Practice Exam'), ('final', 'Final Exam'), ('assessment', 'Assessment')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='has_auto_save',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='has_instant_result',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='has_progress_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='has_random_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='has_timer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='content.instructor'),
        ),
        migrations.AddField(
            model_name='exam',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='rules_policies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='skills_covered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='what_youll_be_tested_on',
            field=models.TextField(blank=True, null=True),
        ),
    ]
