"""
Simple English → Arabic label mapping for the dashboard UI.
This avoids requiring compiled gettext translations in development.
"""

ARABIC_LABELS = {
    # General
    'Overview': 'نظرة عامة',
    'Dashboard': 'لوحة التحكم',
    'Users': 'المستخدمين',
    'Categories': 'الأقسام',
    'Topics': 'المواضيع',
    'Question Topics': 'مواضيع الأسئلة',
    'Sections': 'الأقسام',
    'Exam Sections': 'أقسام الامتحان',
    'Blogs': 'المقالات',
    'Testimonials': 'الآراء',
    'Notifications': 'الإشعارات',
    'Notification Receipts': 'إيصالات الإشعارات',
    'App Info': 'معلومات التطبيق',
    'Contact Messages': 'رسائل التواصل',
    'Support Requests': 'طلبات الدعم',
    'Instructors': 'المحاضرين',
    'AI Instructions': 'تعليمات الذكاء الاصطناعي',
    'Settings': 'الإعدادات',
    'Questions': 'الأسئلة',
    'Answers': 'الإجابات',
    'Question Topics': 'مواضيع الأسئلة',
    'Exam Section Links': 'روابط أقسام الامتحان',
    'Exams': 'الامتحانات',
    'Exam Questions': 'أسئلة الامتحان',
    'User Exams': 'امتحانات المستخدمين',
    'Exam Trials': 'محاولات الامتحان',
    'Exam Trails': 'مسارات الامتحان',
    'Exam Trial Details': 'تفاصيل مسار الامتحان',
    'Trail Categories': 'أقسام المسار',
    'Trail Sub-categories': 'أقسام المسار الفرعية',
    'Trail Sub-sub-categories': 'أقسام المسار الفرعية الأصغر',
    'Trail Sections': 'أقسام المسار',
    'Trail Topics': 'مواضيع المسار',
    'Packages': 'الباقات',
    'Package Sub-categories': 'أقسام الباقة الفرعية',
    'Package Exams': 'امتحانات الباقة',
    'Subscriptions': 'الاشتراكات',
    'Discount Codes': 'أكواد الخصم',
    'Payment Types': 'طرق الدفع',
    'Transactions': 'المعاملات',
    'Money Logs': 'سجلات المال',
    'Card Tokens': 'بطاقات الدفع',
    'Invoices': 'الفواتير',
    'User Profiles': 'ملفات المستخدمين',
    'OTP Requests': 'طلبات OTP',
    'Password Reset Tokens': 'رموز إعادة تعيين كلمة المرور',
    'Audit Logs': 'سجلات التدقيق',

    # Apps
    'Users': 'المستخدمين',
    'Content': 'المحتوى',
    'Exams': 'الامتحانات',
    'Packages': 'الباقات',
    'Payments': 'المدفوعات',

    # Common fields
    'ID': 'المعرف',
    'Name': 'الاسم',
    'Title': 'العنوان',
    'Description': 'الوصف',
    'Content': 'المحتوى',
    'Status': 'الحالة',
    'Created at': 'تاريخ الإنشاء',
    'Updated at': 'تاريخ التعديل',
    'Deleted at': 'تاريخ الحذف',
    'Order': 'الترتيب',
    'Is active': 'نشط',
    'Active': 'نشط',
    'Inactive': 'غير نشط',
    'Pending': 'معلق',
    'Approved': 'مقبول',
    'Rejected': 'مرفوض',
    'Open': 'مفتوح',
    'Closed': 'مغلق',
    'Yes': 'نعم',
    'No': 'لا',
    'Success': 'ناجح',
    'Failed': 'فاشل',
    'Draft': 'مسودة',
    'Sent': 'مرسل',
    'Paid': 'مدفوع',
    'User': 'المستخدم',
    'Phone': 'رقم الهاتف',
    'Email': 'البريد الإلكتروني',
    'First name': 'الاسم الأول',
    'Last name': 'الاسم الأخير',
    'Full name': 'الاسم الكامل',
    'Role type': 'نوع الدور',
    'Admin': 'أدمن',
    'User': 'مستخدم',
    'Accountant': 'محاسب',
    'Data Entry': 'إدخال بيانات',
    'Is staff': 'موظف',
    'Is superuser': 'سوبر أدمن',
    'Is phone verified': 'الهاتف مُفعّل',
    'Is email verified': 'الإيميل مُفعّل',
    'Date joined': 'تاريخ الانضمام',
    'Password': 'كلمة المرور',
    'Confirm password': 'تأكيد كلمة المرور',
    'Password1': 'كلمة المرور',
    'Password2': 'تأكيد كلمة المرور',
    'Category': 'القسم',
    'Parent': 'الأب',
    'Parent Category': 'القسم الأب',
    'Level': 'المستوى',
    'Legacy level indicator: 1=category, 2=sub-category, 3=sub-sub-category': 'مؤشر المستوى: 1=قسم رئيسي، 2=قسم فرعي، 3=قسم فرعي أصغر',
    'Is top': 'مميز',
    'Icon': 'الأيقونة',
    'Foreground color': 'لون المقدمة',
    'Background color': 'لون الخلفية',
    'Topic': 'الموضوع',
    'Section': 'القسم',
    'Image': 'الصورة',
    'Rating': 'التقييم',
    'Question': 'السؤال',
    'Answer': 'الإجابة',
    'Answer option': 'خيار الإجابة',
    'Correct answer': 'الإجابة الصحيحة',
    'Answer type': 'نوع الإجابة',
    'Question type': 'نوع السؤال',
    'Text question': 'نص السؤال',
    'Notes': 'ملاحظات',
    'Hint': 'تلميح',
    'Show answer explanation': 'عرض شرح الإجابة',
    'Show hint': 'عرض التلميح',
    'Show answer': 'عرض الإجابة',
    'Show video': 'عرض الفيديو',
    'Video link': 'رابط الفيديو',
    'Time minutes': 'الوقت (دقيقة)',
    'Duration minutes': 'المدة (دقيقة)',
    'Question has image': 'السؤال يحتوي على صورة',
    'Answer has image': 'الإجابة تحتوي على صورة',
    'Sort order': 'الترتيب',
    'Score': 'النتيجة',
    'Correct answers': 'الإجابات الصحيحة',
    'Wrong answers': 'الإجابات الخاطئة',
    'Start date': 'تاريخ البداية',
    'End date': 'تاريخ النهاية',
    'Exam': 'الامتحان',
    'Package': 'الباقة',
    'Price': 'السعر',
    'Price before discount': 'السعر قبل الخصم',
    'Discount': 'الخصم',
    'Period days': 'المدة بالأيام',
    'Number of questions': 'عدد الأسئلة',
    'Trial count': 'عدد المحاولات',
    'Exam count': 'عدد الامتحانات',
    'Is trial': 'تجريبي',
    'Sub category': 'القسم الفرعي',
    'Sub subcategory': 'القسم الفرعي الأصغر',
    'Sub sub category': 'القسم الفرعي الأصغر',
    'Mode': 'الوضع',
    'Question mode': 'وضع الأسئلة',
    'Is timed mode': 'مؤقت',
    'Question count': 'عدد الأسئلة',
    'Total questions': 'إجمالي الأسئلة',
    'Stages': 'المراحل',
    'Current stage': 'المرحلة الحالية',
    'Is correct': 'صحيح',
    'Is marked': 'معلّم',
    'Is read': 'مقروء',
    'Read at': 'قرأ في',
    'Amount': 'المبلغ',
    'Currency': 'العملة',
    'Is success': 'ناجح',
    'Transaction type': 'نوع العملية',
    'Payment id': 'معرف الدفع',
    'Payment brand': 'شركة الدفع',
    'Gateway transaction id': 'معرف بوابة الدفع',
    'Result summary': 'ملخص النتيجة',
    'Coupon code': 'كود الخصم',
    'Coupon': 'كود الخصم',
    'Platform': 'المنصة',
    'Item': 'العنصر',
    'Unique id': 'المعرف الفريد',
    'Payment id': 'معرف الدفع',
    'Last4': 'آخر 4 أرقام',
    'Brand': 'الشركة',
    'Expiry month': 'شهر الانتهاء',
    'Expiry year': 'سنة الانتهاء',
    'Token': 'التوكن',
    'Invoice number': 'رقم الفاتورة',
    'Total amount': 'الإجمالي',
    'Sent to accounting': 'أُرسلت للمحاسبة',
    'Sent at': 'تاريخ الإرسال',
    'Created by': 'أنشأه',
    'Sent by': 'أرسله',
    'User package': 'اشتراك المستخدم',
    'Action': 'الإجراء',
    'Entity type': 'نوع الكيان',
    'Entity id': 'معرف الكيان',
    'Metadata': 'البيانات الوصفية',
    'Ip address': 'عنوان IP',
    'Attempts': 'المحاولات',
    'Expires at': 'تنتهي في',
    'Verified': 'مُفعّل',
    'Used': 'مُستخدم',
    'Specialization': 'التخصص',
    'Governorate': 'المحافظة',
    'Birth date': 'تاريخ الميلاد',
    'Profile completed': 'اكتمل الملف',
    'Message': 'الرسالة',
    'Mobile': 'الموبايل',
    'Instructions': 'التعليمات',
    'Is default': 'افتراضي',
    'Key': 'المفتاح',
    'Value': 'القيمة',
    'Target users': 'المستخدمون المستهدفون',
    'Limit choices to': 'تقييد الاختيارات',
    'Hold down "Control", or "Command" on a Mac, to select more than one.': 'استمر بالضغط على "Control" أو "Command" على Mac لاختيار أكثر من واحد.',
    'Receipts': 'الإيصالات',
    'Ios version': 'iOS',
    'Android version': 'Android',
    'Web': 'ويب',
    'Mobile': 'موبايل',
    'iOS': 'iOS',
    'Android': 'أندرويد',
    'Tutor Mode': 'وضع المدرّس',
    'Exam Mode': 'وضع الامتحان',
    'Radio': 'اختيار واحد',
    'Multiple Choice': 'اختيار متعدد',
    'Percentage': 'نسبة مئوية',
    'Amount': 'مبلغ',
    'Quantity': 'الكمية',
    'Used count': 'عدد الاستخدام',
    'Marketer': 'المسوق',
    'Type': 'النوع',
    'Code': 'الكود',
}


def to_arabic(value):
    if not value:
        return value
    text = str(value).strip()
    # Exact match
    if text in ARABIC_LABELS:
        return ARABIC_LABELS[text]
    # Title-case / lower-case variants
    if text.lower() in ARABIC_LABELS:
        return ARABIC_LABELS[text.lower()]
    if text.title() in ARABIC_LABELS:
        return ARABIC_LABELS[text.title()]
    # Replace underscores with spaces and try again
    spaced = text.replace('_', ' ').strip()
    if spaced in ARABIC_LABELS:
        return ARABIC_LABELS[spaced]
    if spaced.lower() in ARABIC_LABELS:
        return ARABIC_LABELS[spaced.lower()]
    if spaced.title() in ARABIC_LABELS:
        return ARABIC_LABELS[spaced.title()]
    return text
