# Generated by Django 4.2.30 on 2026-06-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('sent_to_accounting', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoneyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('ios', 'iOS'), ('android', 'Android')], max_length=50)),
                ('unique_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField()),
                ('coupon_code', models.CharField(blank=True, db_column='coupon', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Money Log',
                'verbose_name_plural': 'Money Logs',
                'db_table': 'money_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCardToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255)),
                ('last4', models.CharField(max_length=4)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_month', models.PositiveSmallIntegerField()),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Card Token',
                'verbose_name_plural': 'Payment Card Tokens',
                'db_table': 'users_credit_cards',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Types',
                'db_table': 'payment_types',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(db_column='type', max_length=20)),
                ('payment_id', models.CharField(db_index=True, max_length=100)),
                ('payment_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway_transaction_id', models.CharField(blank=True, db_column='transaction_id', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('is_success', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(blank=True, db_column='coupon', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='packages.package')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'hyperpay_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
