# Generated by Django 4.2.30 on 2026-06-22 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentcardtoken',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_card_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moneylog',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_logs', to='packages.package'),
        ),
        migrations.AddField(
            model_name='moneylog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_by',
            field=models.ForeignKey(blank=True, db_column='sent_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user_package',
            field=models.ForeignKey(db_column='user_package_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='packages.userpackage'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', '-created_at'], name='hyperpay_re_user_id_361c52_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['coupon_code'], name='hyperpay_re_coupon_4dc5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcardtoken',
            index=models.Index(fields=['user', 'is_active'], name='users_credi_user_id_bca046_idx'),
        ),
        migrations.AddIndex(
            model_name='moneylog',
            index=models.Index(fields=['payment_id'], name='money_logs_payment_d4c34c_idx'),
        ),
        migrations.AddIndex(
            model_name='moneylog',
            index=models.Index(fields=['user', '-created_at'], name='money_logs_user_id_a618e5_idx'),
        ),
    ]
